#!/usr/bin/env bash

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME="$(basename "$0")"

function print_usage {
  echo
  echo "Usage: $SCRIPT_NAME [OPTIONS]"
  echo
  echo "This script is used to build all the AMIs used by the Nomad stack."
  echo
  echo "Options:"
  echo
  echo -e "  --region\t\tThe AWS region to build the AMIs in.  Defaults to eu-west-1."
  echo
  echo "Examples:"
  echo
  echo "  $SCRIPT_NAME --region eu-east-1"
}

log() {

  local readonly level="$1"
  local readonly message="$2"
  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")

  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

assert_not_empty() {
  local -r arg_name="$1"
  local -r arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log "ERROR" "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

assert_is_installed() {
  local -r name="$1"

  if [[ ! $(command -v "${name}") ]]; then
    log "ERROR" "The binary '$name' is required by this script but is not installed or in the system's PATH."
    exit 1
  fi
}

assert_exists() {
  local -r path="$1"

  if ! [[ -e "$path" ]]; then
    log "ERROR" "The file '$path' does not exist"
    exit 1
  fi
}

build_amis() {
  local -r region="$1"

  local -r ami_dir="$SCRIPT_DIR/../amis"

  local path
  for path in "$ami_dir"/*/*.json; do

    pushd "$(dirname "$path")" &> /dev/null
      local filename=$(basename "$path")

      log "INFO" "Building $filename AMI"

      packer build \
        -var "region=$region" \
        "$filename"

    popd &> /dev/null

  done

}

run() {
  local region="eu-west-1"

  while [[ $# -gt 0 ]]; do
    local key="$1"

    case "$key" in
      --region)
        assert_not_empty "$key" "$2"
        region="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log "ERROR" "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_is_installed "packer"

  assert_exists "$SCRIPT_DIR/../configuration/tls/ca.crt"
  assert_exists "$SCRIPT_DIR/../configuration/tls/localhost.crt"
  assert_exists "$SCRIPT_DIR/../configuration/tls/localhost.key"

  log "INFO" "Building AMIs in $region..."

  build_amis "$region"

  log "INFO" "Done.  All AMIs built"
}

run "$@"
